AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS lambda for auto-formation purpose.

Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  ApplicationVersion:
    Default: '0.0.1-SNAPSHOT'
    Type: String
    Description: Application Version
  KafkaBootstrapServers:
    Type: String
    Description: Kafka Bootstrap Servers

Resources:
  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: topic-info
      PrimaryKey:
        Name: topicName
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true

  Api:
    Type: AWS::Serverless::Api
    MethodSettings:
      DataTraceEnabled: true
      MetricsEnabled: true
      HttpMethod: '*'
      LoggingLevel: INFO
    AccessLogSetting:
      DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}'
      Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
    Properties:
      Name: KafkaPlatformCrudApi
      StageName: live
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${Api}
      RetentionInDays: 1

  GetTopicDetailsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.details.GetTopicDetailsHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-topic-details'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics/{topic}
            Method: GET
            RestApiId: !Ref Api

  CreateTopicHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.create.CreateTopicHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-create-topic'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics
            Method: POST
            RestApiId: !Ref Api

  DeleteTopicHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.delete.DeleteTopicHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-delete-topic'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics/{topic}
            Method: DELETE
            RestApiId: !Ref Api