AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS lambda for auto-formation purpose.

Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  ApplicationVersion:
    Default: '0.0.1-SNAPSHOT'
    Type: String
    Description: Application Version
  KakfaStackName:
    Type: String
    Description: Kakfa Cluster Stack Name
  KafkaBootstrapServers:
    Type: String
    Description: Kafka Bootstrap Servers
  NetworkingStackName:
    Type: String
    Description: Networking Stack Name

Resources:
  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: topic-info
      PrimaryKey:
        Name: topicName
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true

  Api:
    Type: AWS::Serverless::Api
    MethodSettings:
      DataTraceEnabled: true
      MetricsEnabled: true
      HttpMethod: '*'
      LoggingLevel: INFO
    AccessLogSetting:
      DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}'
      Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
    Properties:
      Name: KafkaPlatformCrudApi
      StageName: live
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${Api}
      RetentionInDays: 1

  CreateTopicHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.create.CreateTopicHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-create-topic'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
              Resource: '*'
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE: ""
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics
            Method: POST
            RestApiId: !Ref Api
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${KakfaStackName}::BastionHostSecurityGroupId'
        SubnetIds:
          Fn::Split:
            - ','
            - Fn::ImportValue: !Sub '${NetworkingStackName}::SubnetsPrivate'
  GetTopicDetailsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.details.GetTopicDetailsHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-topic-details'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
              Resource: '*'
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE: ""
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics/{topic}
            Method: GET
            RestApiId: !Ref Api
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${KakfaStackName}::BastionHostSecurityGroupId'
        SubnetIds:
          Fn::Split:
            - ','
            - Fn::ImportValue: !Sub '${NetworkingStackName}::SubnetsPrivate'

  DeleteTopicHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.delete.DeleteTopicHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Sub '${ApplicationName}-delete-topic'
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
              Resource: '*'
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "ec2:*"
              Resource: '*'
      Tracing: Active
      AutoPublishAlias: live
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref KafkaBootstrapServers
          DYNAMODB_SERVICE_URL_OVERRIDE: ""
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /topics/{topic}
            Method: DELETE
            RestApiId: !Ref Api
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${KakfaStackName}::BastionHostSecurityGroupId'
        SubnetIds:
          Fn::Split:
            - ','
            - Fn::ImportValue: !Sub '${NetworkingStackName}::SubnetsPrivate'

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: !Ref ApplicationName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true

  CognitoUserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: [ 'code', 'implicit' ]
      CallbackURLs: [ 'http://localhost:3000', 'http://localhost:8080' ,'https://localhost', 'https://example.com/authentication' ]
      SupportedIdentityProviders: [ 'COGNITO' ]
      AllowedOAuthScopes: [ 'phone', 'email', 'openid' ]
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  CognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Join [ '-', [ !Ref ApplicationName, !Ref AWS::StackName ] ]
      UserPoolId: !Ref CognitoUserPool

  DeletionAuthorizerHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'target/topic-actions-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.topics.delete.lambdaauthorizer.infra.DeletionAuthorizerHandler'
      Runtime: java11
      Description: Java function
      FunctionName: !Ref ApplicationName
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          ACCOUNT_ID: !Ref AWS::AccountId
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:topic-details'
      Tracing: Active
      AutoPublishAlias: live

Outputs:
  ApiLiveStageUrl:
    Description: "API live stage url"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/live/"
    Export:
      Name: !Sub '${AWS::StackName}::ApiLiveStageUrl'
