AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS lambda for auto-formation purpose.

Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  ApplicationVersion:
    Default: '0.0.1-SNAPSHOT'
    Type: String
    Description: Application Version

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
#      CodeUri: !Sub 'target/${ApplicationName}-${ApplicationVersion}.jar'
      CodeUri: 'target/lambda-authorizer-0.0.1-SNAPSHOT.jar'
      Handler: 'com.example.authorization.infra.Handler'
      Runtime: java11
      Description: Java function
      FunctionName: !Ref ApplicationName
      MemorySize: 256
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      AutoPublishAlias: live